SELECT
  DISTINCT `M`.`MODEL` AS `MODEL`,
  `M`.`COOLING_CAPACITY` AS `COOLING_CAPACITY`,
  `M`.`HEATING_CAPACITY` AS `HEATING_CAPACITY`
FROM
  (
    `LATS_NOISE`.`T_NOISE_MODELSPEC` `N`
    JOIN (
      SELECT
        `LATS_NOISE`.`T_NOISE_ISC_SPEC`.`MODEL` AS `MODEL`,
        `LATS_NOISE`.`T_NOISE_ISC_SPEC`.`COOLING_CAPACITY` AS `COOLING_CAPACITY`,
        `LATS_NOISE`.`T_NOISE_ISC_SPEC`.`HEATING_CAPACITY` AS `HEATING_CAPACITY`
      FROM
        `LATS_NOISE`.`T_NOISE_ISC_SPEC`
      WHERE
        `LATS_NOISE`.`T_NOISE_ISC_SPEC`.`POWER_SUPPLY` = 3
        AND `LATS_NOISE`.`T_NOISE_ISC_SPEC`.`GENERATION` = 3
    ) `M` ON(`N`.`MODEL_NAME` = `M`.`MODEL`)
  )