(
  SELECT
    `LATS_CMN`.`T_CMN_USAGE`.`SEQ` AS `SEQ`,
    `LATS_CMN`.`T_CMN_USAGE`.`PROGRAM` AS `PROGRAM_ORIGIN`,
CASE
      WHEN locate('LATS-HVAC', `LATS_CMN`.`T_CMN_USAGE`.`PROGRAM`) > 0 THEN 'LATS-HVAC'
      WHEN locate('LATS-WPD', `LATS_CMN`.`T_CMN_USAGE`.`PROGRAM`) > 0 THEN 'LATS-WPD'
      WHEN `LATS_CMN`.`T_CMN_USAGE`.`PROGRAM` = 'LATS-AWHP' THEN 'LATS-ThermaV'
      WHEN `LATS_CMN`.`T_CMN_USAGE`.`PROGRAM` = 'LATS-WaterPipeDesign_Global_TEST' THEN 'LATS-WPD'
      ELSE `LATS_CMN`.`T_CMN_USAGE`.`PROGRAM`
    END AS `PROGRAM`,
CASE
      WHEN locate('LATS-HVAC', `LATS_CMN`.`T_CMN_USAGE`.`PROGRAM`) > 0
      AND `LATS_CMN`.`T_CMN_USAGE`.`OS_VERSION` = 'WEB' THEN 'LATS-HVAC-WEB'
      WHEN locate('LATS-HVAC', `LATS_CMN`.`T_CMN_USAGE`.`PROGRAM`) > 0
      AND (
        `LATS_CMN`.`T_CMN_USAGE`.`OS_VERSION` <> 'WEB'
        OR `LATS_CMN`.`T_CMN_USAGE`.`OS_VERSION` IS NULL
      ) THEN 'LATS-HVAC'
      WHEN locate('LATS-WPD', `LATS_CMN`.`T_CMN_USAGE`.`PROGRAM`) > 0 THEN 'LATS-WPD'
      WHEN `LATS_CMN`.`T_CMN_USAGE`.`PROGRAM` = 'LATS-AWHP' THEN 'LATS-ThermaV'
      WHEN `LATS_CMN`.`T_CMN_USAGE`.`PROGRAM` = 'LATS-WaterPipeDesign_Global_TEST' THEN 'LATS-WPD'
      ELSE `LATS_CMN`.`T_CMN_USAGE`.`PROGRAM`
    END AS `PROGRAM_WEB`,
    `LATS_CMN`.`T_CMN_USAGE`.`USER` AS `USER`,
    `LATS_CMN`.`T_CMN_USAGE`.`EMAIL` AS `EMAIL`,
    `LATS_CMN`.`T_CMN_USAGE`.`IP` AS `IP`,
    `LATS_CMN`.`T_CMN_USAGE`.`COMPANY` AS `COMPANY`,
    `LATS_CMN`.`T_CMN_USAGE`.`COUNTRY` AS `COUNTRY`,
    `LATS_CMN`.`T_CMN_USAGE`.`REGION` AS `REGION`,
    `LATS_CMN`.`T_CMN_USAGE`.`REQUEST_CODE` AS `REQUEST_CODE`,
    `LATS_CMN`.`T_CMN_USAGE`.`JOBTYPE` AS `JOBTYPE`,
    `LATS_CMN`.`T_CMN_USAGE`.`USAGETYPE` AS `USAGETYPE`,
    `LATS_CMN`.`T_CMN_USAGE`.`CREATE_DATE` AS `CREATE_DATE`,
    date_format(`LATS_CMN`.`T_CMN_USAGE`.`CREATE_DATE`, '%Y%m') AS `CREATE_MONTH`,
    date_format(`LATS_CMN`.`T_CMN_USAGE`.`CREATE_DATE`, '%Y %b') AS `MONTH`,
    `LATS_CMN`.`T_CMN_USAGE`.`ENTITY` AS `ENTITY`
  FROM
    `LATS_CMN`.`T_CMN_USAGE`
)