SELECT
  `LATS_CMN`.`T_CMN_LANGUAGE`.`CODE` AS `CODE`,
  `LATS_CMN`.`T_CMN_LANGUAGE`.`HVAC_ID` AS `HVAC_ID`,
  `LATS_CMN`.`T_CMN_LANGUAGE`.`ENGLISH` AS `MESSAGE`,
  CONVERT('english' USING utf8mb3) AS `LOCALE`
FROM
  `LATS_CMN`.`T_CMN_LANGUAGE`
UNION
ALL
SELECT
  `LATS_CMN`.`T_CMN_LANGUAGE`.`CODE` AS `CODE`,
  `LATS_CMN`.`T_CMN_LANGUAGE`.`HVAC_ID` AS `HVAC_ID`,
  IFNULL(
    `LATS_CMN`.`T_CMN_LANGUAGE`.`ALBANIAN`,
    `LATS_CMN`.`T_CMN_LANGUAGE`.`ENGLISH`
  ) AS `MESSAGE`,
  CONVERT('albanian' USING utf8mb3) AS `LOCALE`
FROM
  `LATS_CMN`.`T_CMN_LANGUAGE`
UNION
ALL
SELECT
  `LATS_CMN`.`T_CMN_LANGUAGE`.`CODE` AS `CODE`,
  `LATS_CMN`.`T_CMN_LANGUAGE`.`HVAC_ID` AS `HVAC_ID`,
  IFNULL(
    `LATS_CMN`.`T_CMN_LANGUAGE`.`BOSNIAN`,
    `LATS_CMN`.`T_CMN_LANGUAGE`.`ENGLISH`
  ) AS `MESSAGE`,
  CONVERT('bosnian' USING utf8mb3) AS `LOCALE`
FROM
  `LATS_CMN`.`T_CMN_LANGUAGE`
UNION
ALL
SELECT
  `LATS_CMN`.`T_CMN_LANGUAGE`.`CODE` AS `CODE`,
  `LATS_CMN`.`T_CMN_LANGUAGE`.`HVAC_ID` AS `HVAC_ID`,
  IFNULL(
    `LATS_CMN`.`T_CMN_LANGUAGE`.`BULGARIAN`,
    `LATS_CMN`.`T_CMN_LANGUAGE`.`ENGLISH`
  ) AS `MESSAGE`,
  CONVERT('bulgarian' USING utf8mb3) AS `LOCALE`
FROM
  `LATS_CMN`.`T_CMN_LANGUAGE`
UNION
ALL
SELECT
  `LATS_CMN`.`T_CMN_LANGUAGE`.`CODE` AS `CODE`,
  `LATS_CMN`.`T_CMN_LANGUAGE`.`HVAC_ID` AS `HVAC_ID`,
  IFNULL(
    `LATS_CMN`.`T_CMN_LANGUAGE`.`CROATIAN`,
    `LATS_CMN`.`T_CMN_LANGUAGE`.`ENGLISH`
  ) AS `MESSAGE`,
  CONVERT('croatian' USING utf8mb3) AS `LOCALE`
FROM
  `LATS_CMN`.`T_CMN_LANGUAGE`
UNION
ALL
SELECT
  `LATS_CMN`.`T_CMN_LANGUAGE`.`CODE` AS `CODE`,
  `LATS_CMN`.`T_CMN_LANGUAGE`.`HVAC_ID` AS `HVAC_ID`,
  IFNULL(
    `LATS_CMN`.`T_CMN_LANGUAGE`.`CZECH`,
    `LATS_CMN`.`T_CMN_LANGUAGE`.`ENGLISH`
  ) AS `MESSAGE`,
  CONVERT('czech' USING utf8mb3) AS `LOCALE`
FROM
  `LATS_CMN`.`T_CMN_LANGUAGE`
UNION
ALL
SELECT
  `LATS_CMN`.`T_CMN_LANGUAGE`.`CODE` AS `CODE`,
  `LATS_CMN`.`T_CMN_LANGUAGE`.`HVAC_ID` AS `HVAC_ID`,
  IFNULL(
    `LATS_CMN`.`T_CMN_LANGUAGE`.`DANISCH`,
    `LATS_CMN`.`T_CMN_LANGUAGE`.`ENGLISH`
  ) AS `MESSAGE`,
  CONVERT('danisch' USING utf8mb3) AS `LOCALE`
FROM
  `LATS_CMN`.`T_CMN_LANGUAGE`
UNION
ALL
SELECT
  `LATS_CMN`.`T_CMN_LANGUAGE`.`CODE` AS `CODE`,
  `LATS_CMN`.`T_CMN_LANGUAGE`.`HVAC_ID` AS `HVAC_ID`,
  IFNULL(
    `LATS_CMN`.`T_CMN_LANGUAGE`.`GERMAN`,
    `LATS_CMN`.`T_CMN_LANGUAGE`.`ENGLISH`
  ) AS `MESSAGE`,
  CONVERT('dutch' USING utf8mb3) AS `LOCALE`
FROM
  `LATS_CMN`.`T_CMN_LANGUAGE`
UNION
ALL
SELECT
  `LATS_CMN`.`T_CMN_LANGUAGE`.`CODE` AS `CODE`,
  `LATS_CMN`.`T_CMN_LANGUAGE`.`HVAC_ID` AS `HVAC_ID`,
  IFNULL(
    `LATS_CMN`.`T_CMN_LANGUAGE`.`FRENCH`,
    `LATS_CMN`.`T_CMN_LANGUAGE`.`ENGLISH`
  ) AS `MESSAGE`,
  CONVERT('french' USING utf8mb3) AS `LOCALE`
FROM
  `LATS_CMN`.`T_CMN_LANGUAGE`
UNION
ALL
SELECT
  `LATS_CMN`.`T_CMN_LANGUAGE`.`CODE` AS `CODE`,
  `LATS_CMN`.`T_CMN_LANGUAGE`.`HVAC_ID` AS `HVAC_ID`,
  IFNULL(
    `LATS_CMN`.`T_CMN_LANGUAGE`.`GERMAN`,
    `LATS_CMN`.`T_CMN_LANGUAGE`.`ENGLISH`
  ) AS `MESSAGE`,
  CONVERT('german' USING utf8mb3) AS `LOCALE`
FROM
  `LATS_CMN`.`T_CMN_LANGUAGE`
UNION
ALL
SELECT
  `LATS_CMN`.`T_CMN_LANGUAGE`.`CODE` AS `CODE`,
  `LATS_CMN`.`T_CMN_LANGUAGE`.`HVAC_ID` AS `HVAC_ID`,
  IFNULL(
    `LATS_CMN`.`T_CMN_LANGUAGE`.`ITALIANO`,
    `LATS_CMN`.`T_CMN_LANGUAGE`.`ENGLISH`
  ) AS `MESSAGE`,
  CONVERT('italiano' USING utf8mb3) AS `LOCALE`
FROM
  `LATS_CMN`.`T_CMN_LANGUAGE`
UNION
ALL
SELECT
  `LATS_CMN`.`T_CMN_LANGUAGE`.`CODE` AS `CODE`,
  `LATS_CMN`.`T_CMN_LANGUAGE`.`HVAC_ID` AS `HVAC_ID`,
  IFNULL(
    `LATS_CMN`.`T_CMN_LANGUAGE`.`LB_ROMANA`,
    `LATS_CMN`.`T_CMN_LANGUAGE`.`ENGLISH`
  ) AS `MESSAGE`,
  CONVERT('lb_romana' USING utf8mb3) AS `LOCALE`
FROM
  `LATS_CMN`.`T_CMN_LANGUAGE`
UNION
ALL
SELECT
  `LATS_CMN`.`T_CMN_LANGUAGE`.`CODE` AS `CODE`,
  `LATS_CMN`.`T_CMN_LANGUAGE`.`HVAC_ID` AS `HVAC_ID`,
  IFNULL(
    `LATS_CMN`.`T_CMN_LANGUAGE`.`GREEK`,
    `LATS_CMN`.`T_CMN_LANGUAGE`.`ENGLISH`
  ) AS `MESSAGE`,
  CONVERT('greek' USING utf8mb3) AS `LOCALE`
FROM
  `LATS_CMN`.`T_CMN_LANGUAGE`
UNION
ALL
SELECT
  `LATS_CMN`.`T_CMN_LANGUAGE`.`CODE` AS `CODE`,
  `LATS_CMN`.`T_CMN_LANGUAGE`.`HVAC_ID` AS `HVAC_ID`,
  IFNULL(
    `LATS_CMN`.`T_CMN_LANGUAGE`.`MACEDONIAN`,
    `LATS_CMN`.`T_CMN_LANGUAGE`.`ENGLISH`
  ) AS `MESSAGE`,
  CONVERT('macedonian' USING utf8mb3) AS `LOCALE`
FROM
  `LATS_CMN`.`T_CMN_LANGUAGE`
UNION
ALL
SELECT
  `LATS_CMN`.`T_CMN_LANGUAGE`.`CODE` AS `CODE`,
  `LATS_CMN`.`T_CMN_LANGUAGE`.`HVAC_ID` AS `HVAC_ID`,
  IFNULL(
    `LATS_CMN`.`T_CMN_LANGUAGE`.`MONTENEGRIAN`,
    `LATS_CMN`.`T_CMN_LANGUAGE`.`ENGLISH`
  ) AS `MESSAGE`,
  CONVERT('montenegrian' USING utf8mb3) AS `LOCALE`
FROM
  `LATS_CMN`.`T_CMN_LANGUAGE`
UNION
ALL
SELECT
  `LATS_CMN`.`T_CMN_LANGUAGE`.`CODE` AS `CODE`,
  `LATS_CMN`.`T_CMN_LANGUAGE`.`HVAC_ID` AS `HVAC_ID`,
  IFNULL(
    `LATS_CMN`.`T_CMN_LANGUAGE`.`POLISH`,
    `LATS_CMN`.`T_CMN_LANGUAGE`.`ENGLISH`
  ) AS `MESSAGE`,
  CONVERT('polish' USING utf8mb3) AS `LOCALE`
FROM
  `LATS_CMN`.`T_CMN_LANGUAGE`
UNION
ALL
SELECT
  `LATS_CMN`.`T_CMN_LANGUAGE`.`CODE` AS `CODE`,
  `LATS_CMN`.`T_CMN_LANGUAGE`.`HVAC_ID` AS `HVAC_ID`,
  IFNULL(
    `LATS_CMN`.`T_CMN_LANGUAGE`.`PORTUGAL`,
    `LATS_CMN`.`T_CMN_LANGUAGE`.`ENGLISH`
  ) AS `MESSAGE`,
  CONVERT('portugal' USING utf8mb3) AS `LOCALE`
FROM
  `LATS_CMN`.`T_CMN_LANGUAGE`
UNION
ALL
SELECT
  `LATS_CMN`.`T_CMN_LANGUAGE`.`CODE` AS `CODE`,
  `LATS_CMN`.`T_CMN_LANGUAGE`.`HVAC_ID` AS `HVAC_ID`,
  IFNULL(
    `LATS_CMN`.`T_CMN_LANGUAGE`.`SERBIAN`,
    `LATS_CMN`.`T_CMN_LANGUAGE`.`ENGLISH`
  ) AS `MESSAGE`,
  CONVERT('serbian' USING utf8mb3) AS `LOCALE`
FROM
  `LATS_CMN`.`T_CMN_LANGUAGE`
UNION
ALL
SELECT
  `LATS_CMN`.`T_CMN_LANGUAGE`.`CODE` AS `CODE`,
  `LATS_CMN`.`T_CMN_LANGUAGE`.`HVAC_ID` AS `HVAC_ID`,
  IFNULL(
    `LATS_CMN`.`T_CMN_LANGUAGE`.`SLOVENIAN`,
    `LATS_CMN`.`T_CMN_LANGUAGE`.`ENGLISH`
  ) AS `MESSAGE`,
  CONVERT('slovenian' USING utf8mb3) AS `LOCALE`
FROM
  `LATS_CMN`.`T_CMN_LANGUAGE`
UNION
ALL
SELECT
  `LATS_CMN`.`T_CMN_LANGUAGE`.`CODE` AS `CODE`,
  `LATS_CMN`.`T_CMN_LANGUAGE`.`HVAC_ID` AS `HVAC_ID`,
  IFNULL(
    `LATS_CMN`.`T_CMN_LANGUAGE`.`SPANISH`,
    `LATS_CMN`.`T_CMN_LANGUAGE`.`ENGLISH`
  ) AS `MESSAGE`,
  CONVERT('spanish' USING utf8mb3) AS `LOCALE`
FROM
  `LATS_CMN`.`T_CMN_LANGUAGE`
UNION
ALL
SELECT
  `LATS_CMN`.`T_CMN_LANGUAGE`.`CODE` AS `CODE`,
  `LATS_CMN`.`T_CMN_LANGUAGE`.`HVAC_ID` AS `HVAC_ID`,
  IFNULL(
    `LATS_CMN`.`T_CMN_LANGUAGE`.`HUNGARIAN`,
    `LATS_CMN`.`T_CMN_LANGUAGE`.`ENGLISH`
  ) AS `MESSAGE`,
  CONVERT('hungarian' USING utf8mb3) AS `LOCALE`
FROM
  `LATS_CMN`.`T_CMN_LANGUAGE`