SELECT
  `LATS_CMN`.`T_CMN_LANGUAGE`.`CODE` AS `CODE`,
  `LATS_CMN`.`T_CMN_LANGUAGE`.`HVAC_ID` AS `HVAC_ID`,
  `LATS_CMN`.`T_CMN_LANGUAGE`.`ENGLISH` AS `MESSAGE`,
  CONVERT('english' USING utf8mb3) AS `LOCALE`
FROM
  `LATS_CMN`.`T_CMN_LANGUAGE`
UNION
ALL
SELECT
  `LATS_CMN`.`T_CMN_LANGUAGE`.`CODE` AS `CODE`,
  `LATS_CMN`.`T_CMN_LANGUAGE`.`HVAC_ID` AS `HVAC_ID`,
  IFNULL(
    `LATS_CMN`.`T_CMN_LANGUAGE`.`KOREAN`,
    `LATS_CMN`.`T_CMN_LANGUAGE`.`ENGLISH`
  ) AS `MESSAGE`,
  CONVERT('korean' USING utf8mb3) AS `LOCALE`
FROM
  `LATS_CMN`.`T_CMN_LANGUAGE`
UNION
ALL
SELECT
  `LATS_CMN`.`T_CMN_LANGUAGE`.`CODE` AS `CODE`,
  `LATS_CMN`.`T_CMN_LANGUAGE`.`HVAC_ID` AS `HVAC_ID`,
  IFNULL(
    `LATS_CMN`.`T_CMN_LANGUAGE`.`CHINESE`,
    `LATS_CMN`.`T_CMN_LANGUAGE`.`ENGLISH`
  ) AS `MESSAGE`,
  CONVERT('chinese' USING utf8mb3) AS `LOCALE`
FROM
  `LATS_CMN`.`T_CMN_LANGUAGE`
UNION
ALL
SELECT
  `LATS_CMN`.`T_CMN_LANGUAGE`.`CODE` AS `CODE`,
  `LATS_CMN`.`T_CMN_LANGUAGE`.`HVAC_ID` AS `HVAC_ID`,
  IFNULL(
    `LATS_CMN`.`T_CMN_LANGUAGE`.`JAPANESE`,
    `LATS_CMN`.`T_CMN_LANGUAGE`.`ENGLISH`
  ) AS `MESSAGE`,
  CONVERT('japanese' USING utf8mb3) AS `LOCALE`
FROM
  `LATS_CMN`.`T_CMN_LANGUAGE`
UNION
ALL
SELECT
  `LATS_CMN`.`T_CMN_LANGUAGE`.`CODE` AS `CODE`,
  `LATS_CMN`.`T_CMN_LANGUAGE`.`HVAC_ID` AS `HVAC_ID`,
  IFNULL(
    `LATS_CMN`.`T_CMN_LANGUAGE`.`ENGLISH`,
    `LATS_CMN`.`T_CMN_LANGUAGE`.`ENGLISH`
  ) AS `MESSAGE`,
  CONVERT('australia' USING utf8mb3) AS `LOCALE`
FROM
  `LATS_CMN`.`T_CMN_LANGUAGE`
UNION
ALL
SELECT
  `LATS_CMN`.`T_CMN_LANGUAGE`.`CODE` AS `CODE`,
  `LATS_CMN`.`T_CMN_LANGUAGE`.`HVAC_ID` AS `HVAC_ID`,
  IFNULL(
    `LATS_CMN`.`T_CMN_LANGUAGE`.`FRENCH`,
    `LATS_CMN`.`T_CMN_LANGUAGE`.`ENGLISH`
  ) AS `MESSAGE`,
  CONVERT('france' USING utf8mb3) AS `LOCALE`
FROM
  `LATS_CMN`.`T_CMN_LANGUAGE`
UNION
ALL
SELECT
  `LATS_CMN`.`T_CMN_LANGUAGE`.`CODE` AS `CODE`,
  `LATS_CMN`.`T_CMN_LANGUAGE`.`HVAC_ID` AS `HVAC_ID`,
  IFNULL(
    `LATS_CMN`.`T_CMN_LANGUAGE`.`SPANISH`,
    `LATS_CMN`.`T_CMN_LANGUAGE`.`ENGLISH`
  ) AS `MESSAGE`,
  CONVERT('spain' USING utf8mb3) AS `LOCALE`
FROM
  `LATS_CMN`.`T_CMN_LANGUAGE`
UNION
ALL
SELECT
  `LATS_CMN`.`T_CMN_LANGUAGE`.`CODE` AS `CODE`,
  `LATS_CMN`.`T_CMN_LANGUAGE`.`HVAC_ID` AS `HVAC_ID`,
  IFNULL(
    `LATS_CMN`.`T_CMN_LANGUAGE`.`ENGLISH`,
    `LATS_CMN`.`T_CMN_LANGUAGE`.`ENGLISH`
  ) AS `MESSAGE`,
  CONVERT('canada' USING utf8mb3) AS `LOCALE`
FROM
  `LATS_CMN`.`T_CMN_LANGUAGE`
UNION
ALL
SELECT
  `LATS_CMN`.`T_CMN_LANGUAGE`.`CODE` AS `CODE`,
  `LATS_CMN`.`T_CMN_LANGUAGE`.`HVAC_ID` AS `HVAC_ID`,
  IFNULL(
    `LATS_CMN`.`T_CMN_LANGUAGE`.`BRAZILIAN`,
    `LATS_CMN`.`T_CMN_LANGUAGE`.`ENGLISH`
  ) AS `MESSAGE`,
  CONVERT('brazil' USING utf8mb3) AS `LOCALE`
FROM
  `LATS_CMN`.`T_CMN_LANGUAGE`
UNION
ALL
SELECT
  `LATS_CMN`.`T_CMN_LANGUAGE`.`CODE` AS `CODE`,
  `LATS_CMN`.`T_CMN_LANGUAGE`.`HVAC_ID` AS `HVAC_ID`,
  IFNULL(
    `LATS_CMN`.`T_CMN_LANGUAGE`.`ENGLISH`,
    `LATS_CMN`.`T_CMN_LANGUAGE`.`ENGLISH`
  ) AS `MESSAGE`,
  CONVERT('mexico' USING utf8mb3) AS `LOCALE`
FROM
  `LATS_CMN`.`T_CMN_LANGUAGE`